server:
  port: ":8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  host: "localhost"
  port: 5432
  user: "tms"
  password: "tms123"
  dbname: "tms"
  sslmode: "disable"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: "5m"

redis:
  host: "localhost"
  port: 6380
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  use_ssl: false
  bucket_name: "tms-attachments"

smtp:
  host: "localhost"
  port: 1025
  username: ""
  password: ""
  from: "noreply@example.com"

jwt:
  secret: "your-super-secret-jwt-key-change-this-in-production"
  access_token_expiry: "15m"
  refresh_token_expiry: "24h"
  magic_link_expiry: "1h"
  unauth_token_expiry: "24h"

features:
  enable_registration: true
  enable_email_login: true
  enable_magic_links: true
