name: Build and Deploy Guerrilla Mail

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
    paths:
      - 'app/email-server/**'
      - 'manifests/guerrilla-mail.nomad'
      - '.github/workflows/guerrilla-mail.yml'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'app/email-server/**'
      - 'manifests/guerrilla-mail.nomad'
      - '.github/workflows/guerrilla-mail.yml'
  workflow_dispatch: # Allow manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/guerrilla-mail

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-email-${{ hashFiles('app/email-server/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-email-

    - name: Test Go build
      run: |
        cd app/email-server
        go mod tidy
        go build -o guerrilla-mail ./main.go

    - name: Run Go tests
      run: |
        cd app/email-server
        go test ./... -v || echo "No tests found, continuing..."

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHC_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./app/email-server
        file: ./app/email-server/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Tags**: ${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Digest**: ${{ steps.build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Platform**: linux/amd64" >> $GITHUB_STEP_SUMMARY

    - name: Deploy to production
      if: github.event_name != 'pull_request'
      run: |
        echo "Deploying Guerrilla Mail to production..."
        curl --location 'https://shipper.bareuptime.co/deploy/job' \
          --header 'X-Secret-Key: ${{ secrets.DEPLOYMENT_SECRET_KEY }}' \
          --form 'tag_id="${{ github.sha }}"' \
          --form 'job_file=@"manifests/guerrilla-mail.nomad"'
        echo "Deployment request sent successfully"

    - name: Generate deployment summary
      run: |
        echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Job**: guerrilla-mail" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp**: $(date -u)" >> $GITHUB_STEP_SUMMARY
